name: fontconfig
on:
  push:
    branches:
      - main
    tags:
      - 'v[0-9]*'
    paths-ignore:
      - '**/README.md'
jobs:
  build:
    runs-on: windows-2019
    strategy:
      matrix:
        msystem: [MINGW32, MINGW64]
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: actions/checkout@v2
    - uses: msys2/setup-msys2@v2
      with:
        #msystem: MINGW64
        msystem: ${{ matrix.msystem }}
        update: true
        install: >-
          base-devel
          git
          zip
    - name: Install Release Dependencies
      run: |
        pacman --noconfirm -S \
          ${MINGW_PACKAGE_PREFIX}-gcc \
          ${MINGW_PACKAGE_PREFIX}-meson \
          ${MINGW_PACKAGE_PREFIX}-ninja \
          ${MINGW_PACKAGE_PREFIX}-pkg-config \
          ${MINGW_PACKAGE_PREFIX}-gperf
    - name: Release Build
      run: bash build.sh
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: fontconfig
        path: fontconfig.zip
  
  deploy:
    name: Deployment
    runs-on: ubuntu-18.04
    if: startsWith(github.ref, 'refs/tags/')
    needs:
      - build
    steps:
      - name: Set Environment Variables
        run: echo "INSTALL_REF=${GITHUB_REF##*/}" >> "$GITHUB_ENV"
      - uses: actions/download-artifact@v4.1.7
        with:
          name: fontconfig
      - uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.INSTALL_REF }}
          name: ${{ env.INSTALL_REF }}
          draft: false
          prerelease: false
          files:
            fontconfig.zip
