name: fontconfig
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/README.md'
jobs:
  build:
    runs-on: windows-2019
    strategy:
      matrix:
        msystem: [MINGW32, MINGW64]
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: actions/checkout@v2
    - uses: msys2/setup-msys2@v2
      with:
        #msystem: MINGW64
        msystem: ${{ matrix.msystem }}
        update: true
        install: >-
          base-devel
          git
          zip
    - name: Install Release Dependencies
      run: |
        pacman --noconfirm -S \
          ${MINGW_PACKAGE_PREFIX}-gcc \
          ${MINGW_PACKAGE_PREFIX}-meson \
          ${MINGW_PACKAGE_PREFIX}-ninja \
          ${MINGW_PACKAGE_PREFIX}-pkg-config \
          ${MINGW_PACKAGE_PREFIX}-gperf
    - name: Release Build
      run: bash build.sh
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: fontconfig
        path: fontconfig.zip
