name: build
on: [push]
jobs:
  build:
    runs-on: windows-2019
    strategy:
      matrix:
        msystem: [MINGW32, MINGW64]
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: actions/checkout@v2
    - uses: msys2/setup-msys2@v2
      with:
        #msystem: MINGW64
        msystem: ${{ matrix.msystem }}
        update: true
        install: >-
          base-devel
          git
          zip
          wget
          zstd
          xz
    - name: Release Build
      run: bash build.sh
